- name: Servers
  hosts: all
  tasks:
    - name: Configure Sysctl
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        ignoreerrors: true
        sysctl_set: true
    - name: Install & run tailscale
      include_role:
        name: artis3n.tailscale
      vars:
        tailscale_args: "--advertise-exit-node"
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
